[package]
name = "reti"
version = "0.1.0"
authors = ["Armin Widegreen <armin.widegreen@gmail.com>"]

[[bin]]
path = "src/main.rs"
name = "reti"

[dependencies]
tempfile = "*"
rust-ini = "*"
reti-storage = { path = "storage" }
chrono = "*"

[dependencies.clap]
version = "~2.16.1"
features = ["unstable"]
